---
abstract: 'Log output via Twilio SMS Message'
author:
  - 'Graham TerMarsch <cpan@howlingfrog.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  File::Temp: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Sub::Override: '0'
  Test::DiagINC: '0.002'
  Test::More: '0.96'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.024, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Log-Dispatch-Twilio
no_index:
  directory:
    - t
    - xt
requires:
  HTTP::Status: '0'
  Log::Dispatch: '0'
  WWW::Twilio::API: '0'
  namespace::clean: '0'
  perl: '5.010001'
resources:
  bugtracker: https://github.com/bleargh45/Log-Dispatch-Twilio/issues
  homepage: http://metacpan.org/release/Log-Dispatch-Twilio/
  repository: git://github.com/bleargh45/Log-Dispatch-Twilio.git
version: '0.04'
x_generated_by_perl: v5.34.1
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: Artistic-2.0
x_static_install: 1
